<?php

/**
 * @file
 * Contains ipc_weather.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function ipc_weather_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ipc_weather module.
    case 'help.page.ipc_weather':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('IPC custom weather module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function ipc_weather_theme() {
  return [
    'ipc_weather' => [
      'variables' => [
        'title' => NULL,
        'weather_data' => NULL,
      ],
    ],
  ];
}
